### ISSUE TITLE
Gives error while testing the lambda function

### ISSUE THREAD

**Issue by GurpreetVirdi** [adrin-mukherjee/lambda_rest2soap#1]
"errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'soap'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"

**Comment by adrin-mukherjee** [comment]
@GurpreetVirdi- It seems you might not have run the '_npm install_' command to install the module dependencies. The package.json file, it clearly talks about '_soap_' being a dependency.
You could try the following:
1. Download the code zip (lambda_rest2soap-master.zip) and unzip it in your local machine/laptop
2. _cd_ into the lambda_rest2soap-master directory
3. Run the command: _npm install_  (At this point, assuming that you already have node.js and npm installed)
4. The above command would create a folder named node_modules which will essentially contain the dependency modules
5. Zip the contents of the folder lambda_rest2soap-master (note: zip the contents and NOT the folder itself)
6. Finally, use the AWS Lambda console to upload the zip file and test the function

Hope this helps.

**Comment by GurpreetVirdi** [comment]
Worked! Thanks for getting back! Appreciate it.
